Tensor Creation

Create:
- A scalar tensor
- A vector tensor with values `[1, 2, 3, 4]

In [ ]:
import torch

In [ ]:
#Scalar Tensor
X = torch.tensor(4)
print(X)
print(X.ndim)
print(X.shape)

tensor(4)
0
torch.Size([])


In [ ]:
#Vector Tensor
vector_tensor = torch.tensor([1,2,3,4])
print(vector_tensor)
print(vector_tensor.ndim)
print(vector_tensor.shape)

tensor([1, 2, 3, 4])
1
torch.Size([4])


## Tensor Exercises

Create a 2×2 Matrix Tensor

Create a 3D Tensor

Create a 3D tensor with shape `(2, 3, 4)`

In [ ]:
matrix_2_by_2 = torch.tensor([[5,8],[2,9]])
print(matrix_2_by_2)
print(matrix_2_by_2.ndim)
print(matrix_2_by_2.shape)

tensor([[5, 8],
        [2, 9]])
2
torch.Size([2, 2])


In [ ]:
tensor_3d = torch.tensor([[[4,7,1,0],[9,3,5,2],[8,6,4,1]],[[0,2,7,9],[5,1,3,8],[6,4,2,7]]])
print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[4, 7, 1, 0],
         [9, 3, 5, 2],
         [8, 6, 4, 1]],

        [[0, 2, 7, 9],
         [5, 1, 3, 8],
         [6, 4, 2, 7]]])
3
torch.Size([2, 3, 4])


## Tensor Manipulation

Create a tensor with values from 1 to 24.

### Tasks

- Reshape it into:
  - A 2x12 tensor
  - A 3x8 tensor
  - A 2x3x4 tensor
- Extract:
  - The first row
  - The last column
  - A 2x2 submatrix
- Flatten the tensor back into 1D.
- Add a scalar value to every element using broadcasting.

In [ ]:
#Create a tensor with values from 1 to 24
tensor = torch.arange(1,25)
print("Original Tensor:")
print(tensor)
print("Shape:", tensor.shape)

Original Tensor:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
Shape: torch.Size([24])


In [ ]:
#Create a 2x12 tensor
tensor_2_12 = tensor.reshape(2,12)
print(tensor_2_12)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])


# Matrix Multiplication

Given two matrices:

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

$$
B =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

## Tasks

1. Compute the following:
   - Matrix addition: $A + B$
   - Matrix subtraction: $A - B$
   - Element-wise multiplication: $A \odot B$
   - Matrix multiplication: $AB$

2. Compute the transpose of $A$.

3. Compute the determinant of $A$.

4. Compute the inverse of $A$.

5. Verify the following identity:

$$
AA^{-1} = I
$$

where $I$ is the identity matrix.


In [ ]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
Matrix_addition = torch.add(A,B)
Matrix_subtraction = torch.subtract(A,B)
Element_wise_multiplication = A * B
Matrix_Multiplication = torch.matmul(A,B)

In [ ]:
print(Matrix_addition)

tensor([[ 6,  8],
        [10, 12]])


In [ ]:
print(Matrix_subtraction)

tensor([[-4, -4],
        [-4, -4]])


In [ ]:
print(Element_wise_multiplication)

tensor([[ 5, 12],
        [21, 32]])


In [ ]:
print(Matrix_Multiplication)

tensor([[19, 22],
        [43, 50]])


In [ ]:
A_transpose = torch.transpose(A,0,1)
print(A_transpose)

tensor([[1, 3],
        [2, 4]])


Dot Product and Norms

Create:

\[
u = [1, 2, 3]
\]

\[
v = [4, 5, 6]
\]

### Tasks
- Compute:
  - Dot product
  - L1 norm of the dot product
  - L2 norm of the dot product
  - Cosine similarity between the u and v vetors

---


In [ ]:
u = torch.tensor([1,2,3], dtype=torch.float32)
v = torch.tensor([4,5,6], dtype = torch.float32)
dot_product = torch.dot(u,v)
L1_norm = torch.norm(dot_product, p=1)
L2_norm = torch.norm(dot_product, p=2 )
import torch.nn.functional as F
cosine_similarity = F.cosine_similarity(u.unsqueeze(0),v.unsqueeze(0))
print("Dot product:", dot_product.item())
print("L1 norm of dot_product:", L1_norm.item())
print("L2 norm of dot_product:", L2_norm.item())
print("Cosine similarity:", cosine_similarity.item())

Dot product: 32.0
L1 norm of dot_product: 32.0
L2 norm of dot_product: 32.0
Cosine similarity: 0.9746317863464355


## Eigenvalues and Eigenvectors

Create the matrix:

\[
A =
\begin{bmatrix}
7 & 11 \\
5 & 2
\end{bmatrix}
\]

Tasks:
- Compute the eigenvalues
- Compute the eigenvectors
- Print both results

In [44]:
import torch
A = torch.tensor([[7,11],[5,2]], dtype=torch.float32)
eigenvalues, eigenvectors = torch.linalg.eig(A)
print("\n Eigenvalues: \n", eigenvalues)
print("\n Eigenvectors: \n", eigenvectors)


 Eigenvalues: 
 tensor([12.3262+0.j, -3.3262+0.j])

 Eigenvectors: 
 tensor([[ 0.9000+0.j, -0.7291+0.j],
        [ 0.4358+0.j,  0.6844+0.j]])
